// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using library_app.Data;

#nullable disable

namespace libraryapp.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20250222072055_UpdateSeedData3")]
    partial class UpdateSeedData3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("library_app.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 1",
                            Genre = "Fiction",
                            ISBN = "1234567890123",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 2",
                            Genre = "Fiction",
                            ISBN = "1234567890124",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 3",
                            Genre = "Fiction",
                            ISBN = "1234567890125",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author 4",
                            Genre = "Fiction",
                            ISBN = "1234567890126",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author 5",
                            Genre = "Fiction",
                            ISBN = "1234567890127",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author 6",
                            Genre = "Fiction",
                            ISBN = "1234567890128",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author 7",
                            Genre = "Fiction",
                            ISBN = "1234567890129",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Author 8",
                            Genre = "Fiction",
                            ISBN = "1234567890130",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Author 9",
                            Genre = "Fiction",
                            ISBN = "1234567890131",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Author 10",
                            Genre = "Fiction",
                            ISBN = "1234567890132",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 10"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Author 11",
                            Genre = "Fiction",
                            ISBN = "1234567890133",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 11"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Author 12",
                            Genre = "Fiction",
                            ISBN = "1234567890134",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 12"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Author 13",
                            Genre = "Fiction",
                            ISBN = "1234567890135",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 13"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Author 14",
                            Genre = "Fiction",
                            ISBN = "1234567890136",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 14"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Author 15",
                            Genre = "Fiction",
                            ISBN = "1234567890137",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 15"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Author 16",
                            Genre = "Fiction",
                            ISBN = "1234567890138",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 16"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Author 17",
                            Genre = "Fiction",
                            ISBN = "1234567890139",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 17"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Author 18",
                            Genre = "Fiction",
                            ISBN = "1234567890140",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 18"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Author 19",
                            Genre = "Fiction",
                            ISBN = "1234567890141",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 19"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Author 20",
                            Genre = "Fiction",
                            ISBN = "1234567890142",
                            PublishedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 20"
                        });
                });

            modelBuilder.Entity("library_app.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "$2a$10$gMxTU/i6xUqH4VMblDEqROIhGuvxo..jtx8zQ1vWgzfoxtE3tIDo.",
                            Role = "Librarian",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "$2a$10$slTluR99Da/WQSfa.MgS8..dv/78t6xBfUoyvr0TaZhAAOCpSJaA6",
                            Role = "Customer",
                            Username = "user2"
                        },
                        new
                        {
                            Id = 3,
                            Password = "$2a$10$P1A3rkmkgNcGE/0XdI38lOlNE.kOyIa66aUcDKpQGLhIcPtFHmVkm",
                            Role = "Customer",
                            Username = "user3"
                        },
                        new
                        {
                            Id = 4,
                            Password = "$2a$10$UDTCgCaHYKlsM15tgEhnYe8bq5pqzuNUTKrxG6h9j0p7oeXOjkc8O",
                            Role = "Customer",
                            Username = "user4"
                        },
                        new
                        {
                            Id = 5,
                            Password = "$2a$10$CSdlGg45LncmJbkBhQ1S2uWpzWHIktEk.YcJgpm8j6.JS9yYHwiny",
                            Role = "Customer",
                            Username = "user5"
                        },
                        new
                        {
                            Id = 6,
                            Password = "$2a$10$MamEMYuV10V7WDtFYpD.3egBPOmFB.pgokmy2YXip2YgfHhVXc8PW",
                            Role = "Customer",
                            Username = "user6"
                        },
                        new
                        {
                            Id = 7,
                            Password = "$2a$10$xWspv6RpwSMYOlUq6EgTcu9FogWbNBTw1gZgxMKgh6pZ/VTTiohL6",
                            Role = "Customer",
                            Username = "user7"
                        },
                        new
                        {
                            Id = 8,
                            Password = "$2a$10$KNN0UyozG3CWe9D8TZO/bOvdW91o7zYV4.fhcqcvimUgDVXkkRsXe",
                            Role = "Customer",
                            Username = "user8"
                        },
                        new
                        {
                            Id = 9,
                            Password = "$2a$10$whGSxEgewkU5HadAGtU98uC90akvMsryBzBP53BKRatdcrD.jjS86",
                            Role = "Customer",
                            Username = "user9"
                        },
                        new
                        {
                            Id = 10,
                            Password = "$2a$10$ne5VqR6DBOjt/VozxzwhduH0m5OxzWa/z2K0hp8nCi3TWj8ja6cNC",
                            Role = "Customer",
                            Username = "user10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
