// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using library_app.Data;

#nullable disable

namespace libraryapp.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20250222071306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("library_app.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Alejandra Swaniawski",
                            Genre = "Tools",
                            ISBN = "3354225340401",
                            PublishedDate = new DateTime(2019, 7, 26, 4, 6, 11, 321, DateTimeKind.Local).AddTicks(3116),
                            Title = "Omnis nihil enim."
                        },
                        new
                        {
                            Id = 2,
                            Author = "Victor Johnson",
                            Genre = "Books",
                            ISBN = "1864899033827",
                            PublishedDate = new DateTime(2025, 2, 19, 6, 24, 46, 464, DateTimeKind.Local).AddTicks(3606),
                            Title = "Maxime laborum sed."
                        },
                        new
                        {
                            Id = 3,
                            Author = "Amya Kutch",
                            Genre = "Computers",
                            ISBN = "1578362355100",
                            PublishedDate = new DateTime(2016, 5, 7, 2, 35, 19, 515, DateTimeKind.Local).AddTicks(2020),
                            Title = "Qui quasi eos."
                        },
                        new
                        {
                            Id = 4,
                            Author = "Dixie Rodriguez",
                            Genre = "Outdoors",
                            ISBN = "6700362639552",
                            PublishedDate = new DateTime(2023, 5, 12, 0, 4, 44, 928, DateTimeKind.Local).AddTicks(6143),
                            Title = "Eos neque nesciunt."
                        },
                        new
                        {
                            Id = 5,
                            Author = "Jeremie Heller",
                            Genre = "Tools",
                            ISBN = "1197592108500",
                            PublishedDate = new DateTime(2020, 11, 20, 7, 7, 0, 989, DateTimeKind.Local).AddTicks(4972),
                            Title = "Quo dolorem quaerat."
                        },
                        new
                        {
                            Id = 6,
                            Author = "Efrain Mayert",
                            Genre = "Garden",
                            ISBN = "3936669577423",
                            PublishedDate = new DateTime(2015, 8, 30, 22, 43, 55, 357, DateTimeKind.Local).AddTicks(3776),
                            Title = "Perferendis sed laudantium."
                        },
                        new
                        {
                            Id = 7,
                            Author = "Bulah Wyman",
                            Genre = "Sports",
                            ISBN = "8950568190236",
                            PublishedDate = new DateTime(2023, 11, 7, 10, 46, 45, 498, DateTimeKind.Local).AddTicks(7520),
                            Title = "Repudiandae ipsam impedit."
                        },
                        new
                        {
                            Id = 8,
                            Author = "Nicola Pacocha",
                            Genre = "Grocery",
                            ISBN = "8867237083938",
                            PublishedDate = new DateTime(2022, 6, 10, 3, 59, 50, 176, DateTimeKind.Local).AddTicks(3633),
                            Title = "Aspernatur facere earum."
                        },
                        new
                        {
                            Id = 9,
                            Author = "Caroline Bogisich",
                            Genre = "Books",
                            ISBN = "3762037134697",
                            PublishedDate = new DateTime(2018, 5, 1, 11, 19, 18, 174, DateTimeKind.Local).AddTicks(9240),
                            Title = "Distinctio non molestias."
                        },
                        new
                        {
                            Id = 10,
                            Author = "Ima Nikolaus",
                            Genre = "Jewelery",
                            ISBN = "8779517082619",
                            PublishedDate = new DateTime(2018, 9, 2, 16, 12, 17, 650, DateTimeKind.Local).AddTicks(394),
                            Title = "Ut reprehenderit et."
                        },
                        new
                        {
                            Id = 11,
                            Author = "Scottie Connelly",
                            Genre = "Sports",
                            ISBN = "3577415978530",
                            PublishedDate = new DateTime(2023, 8, 24, 3, 21, 31, 239, DateTimeKind.Local).AddTicks(130),
                            Title = "Qui est facere."
                        },
                        new
                        {
                            Id = 12,
                            Author = "Carolyne Donnelly",
                            Genre = "Movies",
                            ISBN = "9470621603552",
                            PublishedDate = new DateTime(2017, 7, 11, 8, 49, 38, 751, DateTimeKind.Local).AddTicks(7854),
                            Title = "Nostrum reiciendis necessitatibus."
                        },
                        new
                        {
                            Id = 13,
                            Author = "Jayne Schaden",
                            Genre = "Industrial",
                            ISBN = "6779695229310",
                            PublishedDate = new DateTime(2017, 8, 13, 2, 38, 19, 969, DateTimeKind.Local).AddTicks(4362),
                            Title = "Aut quo fugit."
                        },
                        new
                        {
                            Id = 14,
                            Author = "Holden Boyle",
                            Genre = "Grocery",
                            ISBN = "8154294888034",
                            PublishedDate = new DateTime(2018, 11, 14, 18, 53, 44, 608, DateTimeKind.Local).AddTicks(6611),
                            Title = "Soluta veritatis culpa."
                        },
                        new
                        {
                            Id = 15,
                            Author = "Kamren Schuppe",
                            Genre = "Tools",
                            ISBN = "9887470588822",
                            PublishedDate = new DateTime(2018, 2, 14, 22, 3, 51, 795, DateTimeKind.Local).AddTicks(6005),
                            Title = "Fugiat quis harum."
                        },
                        new
                        {
                            Id = 16,
                            Author = "Coty Hessel",
                            Genre = "Health",
                            ISBN = "1635895288241",
                            PublishedDate = new DateTime(2021, 9, 10, 10, 14, 13, 467, DateTimeKind.Local).AddTicks(1908),
                            Title = "Qui dignissimos consequatur."
                        },
                        new
                        {
                            Id = 17,
                            Author = "Zachariah Christiansen",
                            Genre = "Jewelery",
                            ISBN = "4122862707661",
                            PublishedDate = new DateTime(2020, 12, 27, 13, 13, 49, 714, DateTimeKind.Local).AddTicks(4004),
                            Title = "Sunt laboriosam sit."
                        },
                        new
                        {
                            Id = 18,
                            Author = "Daryl Wisoky",
                            Genre = "Kids",
                            ISBN = "5315085883369",
                            PublishedDate = new DateTime(2022, 6, 18, 11, 42, 27, 422, DateTimeKind.Local).AddTicks(467),
                            Title = "Accusamus et eaque."
                        },
                        new
                        {
                            Id = 19,
                            Author = "Ana Kutch",
                            Genre = "Music",
                            ISBN = "3144029929281",
                            PublishedDate = new DateTime(2024, 12, 8, 10, 16, 37, 261, DateTimeKind.Local).AddTicks(4974),
                            Title = "Dolor et delectus."
                        },
                        new
                        {
                            Id = 20,
                            Author = "Loren Wilderman",
                            Genre = "Jewelery",
                            ISBN = "6970676161043",
                            PublishedDate = new DateTime(2016, 4, 28, 16, 42, 6, 116, DateTimeKind.Local).AddTicks(8156),
                            Title = "Consectetur omnis quisquam."
                        });
                });

            modelBuilder.Entity("library_app.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "$2a$10$TYxHp12gnslwIFe1NxydteuNlw1rsjglcnoz42NauiraTdVBdcBFu",
                            Role = "Librarian",
                            Username = "Keara65"
                        },
                        new
                        {
                            Id = 2,
                            Password = "$2a$10$N.TDnOquiG/PwOmpegf2RO3ySe1s.9d0RUgNNFtJxOUDEjz4UxqZ.",
                            Role = "Librarian",
                            Username = "Sherwood_Simonis18"
                        },
                        new
                        {
                            Id = 3,
                            Password = "$2a$10$qCNQG/vjmy.ZrweTSISfjus8ugyJNJxujlZliUp3OSRBCDkSOxqsu",
                            Role = "Librarian",
                            Username = "Elenora.Waters"
                        },
                        new
                        {
                            Id = 4,
                            Password = "$2a$10$taPunFSURZQCXDBjf5x8.eeLN0X.g2JRAgBwQ.nDQoyfGiqnu/JbO",
                            Role = "Librarian",
                            Username = "Percy_Waters"
                        },
                        new
                        {
                            Id = 5,
                            Password = "$2a$10$GnsjF.cCdpcwWIyySZRjYO.bwAQjXsU7gjVcmj.rvzNA.EJ0XEzMm",
                            Role = "Librarian",
                            Username = "Andreanne_Cassin"
                        },
                        new
                        {
                            Id = 6,
                            Password = "$2a$10$jq3ZstOsYq.eDb9wCnTMYunhLTmZWLg8F1er4650MSc33tJI7QxtO",
                            Role = "Customer",
                            Username = "Angelina98"
                        },
                        new
                        {
                            Id = 7,
                            Password = "$2a$10$ZQaAlkyVOs0PZN.h.KfRce./mQy8kmuZY87Aw5ixV7TvnwUZ00Ig6",
                            Role = "Librarian",
                            Username = "Jovani_Dach51"
                        },
                        new
                        {
                            Id = 8,
                            Password = "$2a$10$IWrMxwFEWom/1wolmTVEPuK0DmSwD86ohFYxDZEeH2fNHXpfIhp62",
                            Role = "Customer",
                            Username = "Henry_Kuvalis2"
                        },
                        new
                        {
                            Id = 9,
                            Password = "$2a$10$o7iWzDqiTEz5Q3LpvRcQ0OsRiIec5FmeN38HLFQk/CXNsKIstDMw.",
                            Role = "Customer",
                            Username = "Xzavier_Prohaska69"
                        },
                        new
                        {
                            Id = 10,
                            Password = "$2a$10$K8vm.FYqN70aXjae/83gWuiu.Kqa6WC8y7WXHTSlZZTw/8QyjELrW",
                            Role = "Customer",
                            Username = "Wilfred.Spencer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
